Automatic OSPF router-id assignment.
MERAprojects/ops-quagga pull request #28
Opened 2016-09-20 14:39 UTC by xschily

Tags: fix, dev, Github issue #19

Change-Id: I70fff570e788dbc7025870c757a3a4baaa2e9f0d
Signed-off-by: Ilya Schepin <ischepin@mera.ru>

There are certain rules to assign OSPF (and BGP) router-ids automatically in case the user did not select the id manually. When id is assigned automatically, OSPF will pick it from zebra using zclient API (1st issue, according to OpenSwitch architecture there must be no interaction between components except interaction through OVSDB). OSPF will not write router-id retrieved from zebra to OSPF_Router table (2nd issue, CLI will print everyone except OSPF_Router:router_id as OSPF neighbor in `show ip ospf neighbor` command).  

Router-id should be obtained from OVSDB as BGP does it; using OVSDB table VRF, column active_router_id. Router-id should be written to OVSDB table OSPF_Router by OSPFD when assigned automatically.

2016-10-04 09:58 UTC, stroykov requested changes

2016-10-04 09:58 UTC, stroykov commented on ospfd/ospf_ovsdb_if.c
> +ospf_set_router_id_from_vrf (const struct ovsrec_ospf_router *ovs_ospf_router,
rename to "ospf_router_ovsdb_router_id_update"

2016-10-04 09:58 UTC, stroykov commented on ops-tests/component/ospf/test_ospfv2_ct_verify_config.py
> +    sw("ip address %s/24" % lo2_addr)
/32

2016-10-04 09:58 UTC, stroykov commented on ops-tests/component/ospf/test_ospfv2_ct_verify_config.py
> +    sw("ip address %s/24" % ospf_auto_router_id)
/32

2016-10-07 08:04 UTC, vkarpov commented
No more comments.

2016-10-10 10:33 UTC, apolovin approved these changes
Ok for me

2016-10-14 13:36 UTC, closed without merging